### ISSUE TITLE
After install in HOOBS, Homebridge istance goes down

### ISSUE THREAD

**Issue by alessiobulfaro** [MartinPham/homebridge-homekit-controller#6]
Installed plugin via HOOBS 3.1.22, after install the homebridge service goes down and won't start.
![Schermata 2020-03-13 alle 09 36 24](https://user-images.githubusercontent.com/58361310/76604043-4b919100-650e-11ea-8b03-d05aa2b750b2.png)

**Comment by Midnight83** [comment]
after install server is down
